const chapterContents = {
    spaces: {
      title: 'Metric Spaces, Normed Spaces, Inner Product Spaces',
      image: './images/funanal/Drum_vibration_mode12.gif',
      path: 'spaces',
      subsections: [
        "Metric Spaces Definition",
        "Metric Space Example 1",
        "Metric Space Example 2",
        "Normed Linear Space Definition",
        "Normed Linear Space Example 1",
        "Normed Linear Space Example 2",
        "Norm Metric Theorem 1.1",
        "Inner Product Norm Theorem 1.2",
        "Cauchy-Bunyakovskii-Schwarz Inequality",
        "Sequence metricSpaces",
        "Little l p",
        "A discussion on Dimensions",
      ],
      content: "Detailed content for Metric Spaces...",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
  
    metricSpaces: {
      title: 'Topology of Metric Spaces',
      image: './images/funanal/Möbius_strip.jpg',
      path: 'metricSpaces',
      subsections: ["topology test 1", "topology test 2", "topology test 3"],
      content: "Deep dive into the Topology of Metric Spaces...",
      youtubeChannelId: "UC_x5XG1OV2P6uZZ5FSM9Ttw",
    },
    measureIntegration: {
      title: 'Measure and Integration',
      image: './images/funanal/MeasureTheory.png',
      path: 'measureIntegration',
      subsections: ["measure test 1", "measure test 2", "measure test 3"],
      content: "Exploring the fundamentals of Measure and Integration...",
      youtubeChannelId: "UC_x5XG1OV2P6uZZ5FSM9Ttw",
    },
    fourier: {
      title: 'Fourier Analysis in Hilbert Space',
      image: './images/funanal/Fourier.png',
      path: 'fourier',
      subsections: ["fourier test 1", "fourier test 2", "fourier test 3"],
      content: "Introduction to Fourier Analysis in the context of Hilbert Spaces...",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    linearOpTheory: {
      title: 'An Introduction to Abstract Linear Operator Theory',
      image: './images/funanal/DeSKO.png',
      path: 'linearOpTheory',
      subsections: ["linear op test 1", "linear op test 2", "linear op test 3"],
      content: "Abstract Linear Operator Theory and its applications...",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    MultiCalc: {
      title: 'Multivariable Calculus',
      image: './images/diffgeo/MultiCalc.jpg',
      path: 'MultiCalc',
      subsections: ["MultiCalc test 1", "MultiCalc test 2", "MultiCalc Test 3"],
      content: "Content for Multivariable Calculus...",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    forms: {
      title: 'Forms',
      image: './images/diffgeo/Forms.png',
      path: 'forms',
      subsections: ["forms test 1", "forms test 2", "forms Test 3"],
      content: "hello this is forms content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    diffForms: {
      title: 'Differential Forms',
      image: './images/diffgeo/DifferentialForms.jpg',
      path: 'diffForms',
      subsections: ["diffForms test 1", "diffForms test 2", "diffForms Test 3"],
      content: "hello this is diffForms content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    diffOfDiffForms: {
      title: 'Differentiation of Differential Forms',
      image: './images/diffgeo/DiffofDiffForms.png',
      path: 'diffOfDiffForms',
      subsections: [
        "diffOfDiffForms test 1",
        "diffOfDiffForms test 2",
        "diffOfDiffForms Test 3",
      ],
      content: "hello this is diffOfDiffForms content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    stokes: {
      title: 'Stokes Theorem',
      image: './images/diffgeo/Stokes.png',
      path: 'stokes',
      subsections: ["stokes test 1", "stokes test 2", "stokes Test 3"],
      content: "hello this is stokes content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    manifolds: {
      title: 'Manifolds',
      image: './images/diffgeo/Manifolds.png',
      path: 'manifolds',
      subsections: ["manifolds test 1", "manifolds test 2", "manifolds Test 3"],
      content: "hello this is manifolds content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
    diffGeoDiffForms: {
      subsections: [
        "diffGeoDiffForms test 1",
        "diffGeoDiffForms test 2",
        "diffGeoDiffForms test 3",
      ],
      content: "hello this is diffGeoDiffForms content",
      youtubeChannelId: "UCw2L9e-QtC2E7-LHgC25QwA",
    },
  };
  
  export default chapterContents;
  